// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEE1-oqzYkjJchX9DvOnwinzc7ILuR_9A',
    appId: '1:580030326193:web:9b88dd78d912c5baa08990',
    messagingSenderId: '580030326193',
    projectId: 'quizzle-demo-40bfe',
    authDomain: 'quizzle-demo-40bfe.firebaseapp.com',
    storageBucket: 'quizzle-demo-40bfe.appspot.com',
    measurementId: 'G-9G6KW54SHK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFMb7LaaYxjM5Fhq4dxZMem3jneLrgIEg',
    appId: '1:580030326193:android:23b6d0d0735abf55a08990',
    messagingSenderId: '580030326193',
    projectId: 'quizzle-demo-40bfe',
    storageBucket: 'quizzle-demo-40bfe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBF_NNYGwS9kePqDPm9OY4D1dcNtYYrwW8',
    appId: '1:580030326193:ios:4be5b434963b2084a08990',
    messagingSenderId: '580030326193',
    projectId: 'quizzle-demo-40bfe',
    storageBucket: 'quizzle-demo-40bfe.appspot.com',
    iosClientId: '580030326193-unao2vf13lvqp1pvc33116k76nbg9hbr.apps.googleusercontent.com',
    iosBundleId: 'com.codefox.quizzle',
  );
}
